Enhanced Setup instructions and Improved env Configuration Management
cheshire-cat-ai/local-cat pull request #18
Opened 2024-06-12 10:43 UTC by MRColorR

This pull request introduces some small enhancements to improve the flexibility and ease of setup, updates, and customization:

- **GitIgnore Enhancements:**
  - Updated `.gitignore` to exclude all content of the `cat` folder, not just nested directories.

- **Removed Redundant File:**
  - Deleted `metadata.json` file as it is unnecessary for tracking in GIT. This change simplifies the setup process since the file was frequently altered by user edits, complicating updates ( want to update by pull ? you need to stash first. gitignoring the file fixes this).
  
- **README Updates:**
  - Expanded the README to include a full step-by-step setup guide.
  - Implemented minor improvements to clarify the setup process and enhance user understanding.

- **Security Protocol Configuration:**
  - Uncommented `CORE_USE_SECURE_PROTOCOLS` in .env.example and adjusted its default setting. This adjustment ensures users don't miss it when moving to an actual `.env` file.

- **Environmental Variables:**
  - Added `OLLAMA_PORT` and `OLLAMA_HOST` variable in `.env.example` to simplfy custom configuration process.
  
- **Parameterized Exposed Ports:**
  - All ports are now parameterized, reducing hardcoding, making it easier to customize and switch between exposing and publishing ports. Users can simply comment out the `expose` section and add the same parameterized port inside the new `ports` section, leveraging the already existing env variable.

These improvements are aimed at making the setup and customization process as smooth as possible while maintaining quite the same logic for already existing users.

2024-06-12 10:52 UTC, MRColorR commented
I hope you find these updates beneficial. 
The primary goal with these changes was to minimize the need for hardcoding and extensive code modifications during customization and setup. By parameterizing settings any necessary adjustments are straightforward. This should help in reducing discrepancies between individual customizations and the base code.

After this, i promise I'll give everyone some time to rest :) 
Looking forward to your feedback!

2024-06-12 11:25 UTC, pieroit commented
Thanks @MRColorR seems a nice improvement 
Regarding mettadata.json, it was there because people always get wrong the ollama config in the cat.
Id there is no metadata.json, there should be at least a screenshot in the readme

2024-06-12 12:13 UTC, MRColorR commented
> Thanks @MRColorR seems a nice improvement Regarding mettadata.json, it was there because people always get wrong the ollama config in the cat. Id there is no metadata.json, there should be at least a screenshot in the readme (just saw it awesome)
> 
> Let's see how it goes! Welcome :)

thanks to you all for the awesome framework.
To make it even clearer, i could add a screenshot for LLM settings and another one for Embedder settings but then i'll need to create an assets folder in the repository just for two png files. 

i wonder how did you manage to put the video inside the readme of cheshirecat core in an assets folder without making it appear in the repo browser. i'm sure i'm missing something easy 😅😄

2024-06-12 16:53 UTC, pieroit commented
> > Thanks @MRColorR seems a nice improvement Regarding mettadata.json, it was there because people always get wrong the ollama config in the cat. Id there is no metadata.json, there should be at least a screenshot in the readme (just saw it awesome)
> > Let's see how it goes! Welcome :)
> 
> thanks to you all for the awesome framework. To make it even clearer, i could add a screenshot for LLM settings and another one for Embedder settings but then i'll need to create an assets folder in the repository just for two png files.
> 
> i wonder how did you manage to put the video inside the readme of cheshirecat core in an assets folder without making it appear in the repo browser. i'm sure i'm missing something easy 😅😄

I don't remember, prolly drag and drop of the video in the readme editor on github?

2024-06-12 17:33 UTC, MRColorR commented
> > > Thanks @MRColorR seems a nice improvement Regarding mettadata.json, it was there because people always get wrong the ollama config in the cat. Id there is no metadata.json, there should be at least a screenshot in the readme (just saw it awesome)
> > > Let's see how it goes! Welcome :)
> > 
> > 
> > thanks to you all for the awesome framework. To make it even clearer, i could add a screenshot for LLM settings and another one for Embedder settings but then i'll need to create an assets folder in the repository just for two png files.
> > i wonder how did you manage to put the video inside the readme of cheshirecat core in an assets folder without making it appear in the repo browser. i'm sure i'm missing something easy 😅😄
> 
> I don't remember, prolly drag and drop of the video in the readme editor on github?

so maybe it's encoded in the readme or it has been put somewhere from github itself, IDK. That's kinda funny.

Anyway i've put two screenshots inside an assets folder: feel free to move/delete them and their folder after the merge if you find a better approach

2024-06-12 21:45 UTC, valentimarco reviewed
I don't like the photos, this repo is for ppl that have a little knowleadge of docker and had tried the cat...

2024-06-12 21:48 UTC, valentimarco commented
Also move the target to `develop` so we can edit without breaking the main

2024-06-13 08:11 UTC, MRColorR commented
> Also move the target to `develop` so we can edit without breaking the main

Thank you for the feedback.

- The `assets` folder and screenshots have been removed as suggested.
- The pull request now targets the upstream `develop` branch. 
  - A minor merge conflict in the `README.md` file has been addressed, and it should now be ready for review.

2024-06-13 16:50 UTC, MRColorR commented
i've added the extra hosts line into the main docker compose like discussed on discord

2024-06-13 18:08 UTC, valentimarco requested changes
Looks good to me but the metadata.json is the core of the repo, so revert the delete commit

2024-06-13 18:08 UTC, valentimarco commented on cat/data/metadata.json
this cannot be deleted, is the core of the repo

2024-06-13 19:16 UTC, MRColorR commented on cat/data/metadata.json
I see. The problem with metadata.json is that as soon as the user edits something like the model, embeddings, and so on, Git complains about the changes and refuses any pull (or push) operations.

It is not uncommon to just Git pull changes to keep the local repository updated, and that file forces users to stash all their settings just to update. 

In any case, if they drop their configuration to update then they have to reconfigure again.
 Is very easy that at some point, or just at the start, when pulling the initial model, the user will choose a different model, making the presence of the existing metadata.json file more of an issue than a shortcut.

I think the detailed step-by-step guide in the new Readme could suffice, removing the need to track a file that is normally created at runtime.

I'd like to discuss it more to better understand your thoughts. 
---
I was also wondering if it's possible to separate the default settings from the users settings to offer users the best of the two worlds.  this will require a rework on cat core repo though,  to manage for example a metadata_default.json containing an example configuration and if the user changes something then save new settings in a gitignored file like metadata_user.json and the cat should at startup check if a metadata_user.json exists if not then load default.

2024-06-13 19:43 UTC, valentimarco commented on cat/data/metadata.json
the metadata.json is under cat/data that is in `.gitignore`, infact i dont have problem with that...
If you have this bug, is a problem of your git...

2024-06-13 19:44 UTC, valentimarco commented on cat/data/metadata.json
This repo is not a tutorial, is a simple `plug and play`... There are guides in the blog and are sufficient

2024-06-13 19:46 UTC, valentimarco commented on cat/data/metadata.json
> I was also wondering if it's possible to separate the default settings from the users settings to offer users the best of the two worlds. this will require a rework on cat core repo though, to manage for example a metadata_default.json containing an example configuration and if the user changes something then save new settings in a gitignored file like metadata_user.json and the cat should at startup check if a metadata_user.json exists if not then load default.

Same as above, this repo is a plug and play installation with all stuff local and offline

2024-06-13 21:45 UTC, MRColorR commented on cat/data/metadata.json
> the metadata.json is under cat/data that is in `.gitignore`, infact i dont have problem with that... If you have this bug, is a problem of your git...

in gitignore i had cat/data** that's ignore all the subdirectories escluding files. i moved to cat/data* to ignore the metadata.json file . if it was ignore the file won't  be tracked in the first place.

2024-06-13 21:55 UTC, MRColorR commented on cat/data/metadata.json
> > I was also wondering if it's possible to separate the default settings from the users settings to offer users the best of the two worlds. this will require a rework on cat core repo though, to manage for example a metadata_default.json containing an example configuration and if the user changes something then save new settings in a gitignored file like metadata_user.json and the cat should at startup check if a metadata_user.json exists if not then load default.
> 
> Same as above, this repo is a plug and play installation with all stuff local and offline

I will proceed with restoring the previously removed file tomorrow. While I aknowledge your decision, I must express my concerns. This approach push the users to download a specific model, which may not be their preference. Additionally, this could impose a maintenance burden to update the file regularly, with the release of superior models.

Despite my reservations about the process and its implications, I trust that we are all working towards the best path :)

2024-06-13 22:23 UTC, merged